#pragma once
#include <utils.h>
#include <lai/core.h>
#include <lai/host.h>
#include <lai/helpers/pci.h>
#include <lai/helpers/pm.h>
#include <lai/helpers/sci.h>
#include <lai/helpers/resource.h>
#include <lai/helpers/pc-bios.h>